### ISSUE TITLE
CT: Assertion failed: reentry detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/hookes-law#64]
```
hookes-law : fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=0.1063829787234043, oldValue=0.10638297872340426
Error: Assertion failed: reentry detected, value=0.1063829787234043, oldValue=0.10638297872340426
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536061958231:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536061958231:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536061958231:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536061958231:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/SingleSpringSystem.js?bust=1536061958231:52:40)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536061958231:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536061958231:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536061958231:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536061958231:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=1000, oldValue=940
Error: Assertion failed: reentry detected, value=1000, oldValue=940
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536061958231:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536061958231:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536061958231:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536061958231:86:30)
    at handleTrackEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/sun/js/SliderTrack.js?bust=1536061958231:95:23)
    at drag (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/sun/js/SliderTrack.js?bust=1536061958231:112:9)
    at Object.move (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/scenery/js/input/SimpleDragHandler.js?bust=1536061958231:199:29)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/scenery/js/input/Input.js?bust=1536061958231:1352:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/scenery/js/input/Input.js?bust=1536061958231:1308:12)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=0.12658227848101267, oldValue=0.127
Error: Assertion failed: reentry detected, value=0.12658227848101267, oldValue=0.127
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536065542129:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536065542129:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536065542129:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536065542129:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/Spring.js?bust=1536065542129:183:33)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536065542129:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536065542129:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536065542129:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536065542129:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: reentry detected, value=-0.040000000000000036, oldValue=-0.04
Error: Assertion failed: reentry detected, value=-0.040000000000000036, oldValue=-0.04
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536064130300:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/SingleSpringSystem.js?bust=1536064130300:52:40)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536064130300:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: reentry detected, value=0.1, oldValue=-0.040000000000000036
Error: Assertion failed: reentry detected, value=0.1, oldValue=-0.040000000000000036
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536064130300:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/Spring.js?bust=1536064130300:183:33)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536064130300:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064130300:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: reentry detected, value=0.9349999999999999, oldValue=0.935
Error: Assertion failed: reentry detected, value=0.9349999999999999, oldValue=0.935
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066294670:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066294670:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066294670:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536066294670:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/Spring.js?bust=1536066294670:183:33)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536066294670:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066294670:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066294670:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066294670:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=0.09800000000000007, oldValue=0.09800000000000009
Error: Assertion failed: reentry detected, value=0.09800000000000007, oldValue=0.09800000000000009
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536063217174:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/Spring.js?bust=1536063217174:183:33)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536063217174:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=0.5, oldValue=0.09800000000000007
Error: Assertion failed: reentry detected, value=0.5, oldValue=0.09800000000000007
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536063217174:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/SingleSpringSystem.js?bust=1536063217174:52:40)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536063217174:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536063217174:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=-0.10000000000000009, oldValue=-0.1
Error: Assertion failed: reentry detected, value=-0.10000000000000009, oldValue=-0.1
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066039380:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066039380:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066039380:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536066039380:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/SingleSpringSystem.js?bust=1536066039380:52:40)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536066039380:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066039380:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066039380:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536066039380:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=0.0024999999999999467, oldValue=0.0025
Error: Assertion failed: reentry detected, value=0.0024999999999999467, oldValue=0.0025
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536068955557:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/systems/model/ParallelSystem.js?bust=1536068955557:122:52)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536068955557:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=0.0022222222222222222, oldValue=0.0024999999999999467
Error: Assertion failed: reentry detected, value=0.0022222222222222222, oldValue=0.0024999999999999467
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536068955557:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/Spring.js?bust=1536068955557:196:35)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536068955557:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536068955557:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : phet-io-tests
7 out of 7 tests passed. 0 failed.

Approximately 9/4/2018, 5:33:55 AM
hookes-law : xss-fuzz : run
Uncaught Error: Assertion failed: reentry detected, value=-0.010000000000000009, oldValue=-0.01
Error: Assertion failed: reentry detected, value=-0.010000000000000009, oldValue=-0.01
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536062179472:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536062179472:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536062179472:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536062179472:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/SingleSpringSystem.js?bust=1536062179472:52:40)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536062179472:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536062179472:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536062179472:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536062179472:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : xss-fuzz : run
Uncaught Error: Assertion failed: reentry detected, value=0.21739130434782616, oldValue=0.21739130434782608
Error: Assertion failed: reentry detected, value=0.21739130434782616, oldValue=0.21739130434782608
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064569599:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064569599:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064569599:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536064569599:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/systems/model/ParallelSystem.js?bust=1536064569599:122:52)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536064569599:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064569599:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064569599:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064569599:230:16)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : xss-fuzz : run
Uncaught Error: Assertion failed: reentry detected, value=600, oldValue=260
Error: Assertion failed: reentry detected, value=600, oldValue=260
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064569599:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064569599:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536064569599:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536064569599:86:30)
    at handleTrackEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/sun/js/SliderTrack.js?bust=1536064569599:95:23)
    at drag (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/sun/js/SliderTrack.js?bust=1536064569599:112:9)
    at Object.move (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/scenery/js/input/SimpleDragHandler.js?bust=1536064569599:199:29)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/scenery/js/input/Input.js?bust=1536064569599:1352:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/scenery/js/input/Input.js?bust=1536064569599:1308:12)
Approximately 9/4/2018, 5:33:55 AM
hookes-law : xss-fuzz : run
Uncaught Error: Assertion failed: reentry detected, value=0.36700000000000005, oldValue=0.367
Error: Assertion failed: reentry detected, value=0.36700000000000005, oldValue=0.367
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/assert/js/assert.js:22:13)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536067273013:301:19)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536067273013:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536067273013:230:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/NumberProperty.js?bust=1536067273013:86:30)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/hookes-law/js/common/model/Spring.js?bust=1536067273013:183:33)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Emitter.js?bust=1536067273013:180:49)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536067273013:304:29)
    at NumberProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536067273013:287:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1536060835006/axon/js/Property.js?bust=1536067273013:230:16)
Approximately 9/4/2018, 5:33:55 AM
```

**Comment by pixelzoom** [comment]
Duplicate of https://github.com/phetsims/hookes-law/issues/63#issuecomment-418212537.

**Comment by KatieWoe** [comment]
Sorry about that.

**Comment by pixelzoom** [comment]
No need to be sorry! I'm glad you reported it.
