### ISSUE TITLE
CT Tandem was required but not supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/hookes-law#77]
```
hookes-law : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/hookes-law_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/assert/js/assert.js?bust=1585883581219:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/Tandem.js:113:19)
    at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/PhetioObject.js:355:17)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/PhetioObject.js:189:10)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/axon/js/Property.js:67:5)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/axon/js/BooleanProperty.js:45:5)
    at new AquaRadioButton (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/sun/js/AquaRadioButton.js:73:26)
    at new AquaRadioButtonGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/sun/js/AquaRadioButtonGroup.js:94:27)
    at new SystemsVisibilityControls (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/js/systems/view/SystemsVisibilityControls.js:133:30)
    at new SystemsScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/js/systems/view/SystemsScreenView.js:39:32)
id: Bayes Chrome
Approximately 4/2/2020, 6:36:58 PM
hookes-law : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/hookes-law_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/assert/js/assert.js?bust=1585892741238:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/Tandem.js:113:19)
    at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/PhetioObject.js:355:17)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/PhetioObject.js:189:10)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/axon/js/Property.js:67:5)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/axon/js/BooleanProperty.js:45:5)
    at new AquaRadioButton (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/sun/js/AquaRadioButton.js:73:26)
    at new AquaRadioButtonGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/sun/js/AquaRadioButtonGroup.js:94:27)
    at new SystemsVisibilityControls (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/js/systems/view/SystemsVisibilityControls.js:133:30)
    at new SystemsScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/js/systems/view/SystemsScreenView.js:39:32)
id: Bayes Chrome
Approximately 4/2/2020, 6:36:58 PM
hookes-law : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/hookes-law_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/assert/js/assert.js?bust=1585883581219:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/Tandem.js:113:19)
    at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/PhetioObject.js:355:17)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/PhetioObject.js:189:10)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/axon/js/Property.js:67:5)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/axon/js/BooleanProperty.js:45:5)
    at new AquaRadioButton (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/sun/js/AquaRadioButton.js:73:26)
    at new AquaRadioButtonGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/sun/js/AquaRadioButtonGroup.js:94:27)
    at new SystemsVisibilityControls (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/js/systems/view/SystemsVisibilityControls.js:133:30)
    at new SystemsScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/js/systems/view/SystemsScreenView.js:39:32)
id: Bayes Chrome
Approximately 4/2/2020, 6:36:58 PM
hookes-law : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/hookes-law_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/assert/js/assert.js?bust=1585892741238:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/Tandem.js:113:19)
    at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/PhetioObject.js:355:17)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/tandem/js/PhetioObject.js:189:10)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/axon/js/Property.js:67:5)
    at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/axon/js/BooleanProperty.js:45:5)
    at new AquaRadioButton (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/sun/js/AquaRadioButton.js:73:26)
    at new AquaRadioButtonGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/sun/js/AquaRadioButtonGroup.js:94:27)
    at new SystemsVisibilityControls (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/js/systems/view/SystemsVisibilityControls.js:133:30)
    at new SystemsScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/hookes-law/js/systems/view/SystemsScreenView.js:39:32)
id: Bayes Chrome
Approximately 4/2/2020, 6:36:58 PM
hookes-law : phet-io-tests : assert
https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/phet-io-wrappers/phet-io-wrappers-tests.html?sim=hookes-law&phetioDebug
9 out of 9 tests passed. 0 failed.

Approximately 4/2/2020, 6:36:58 PM
hookes-law : phet-io-tests : no-assert
https://bayes.colorado.edu/continuous-testing/snapshot-1585874218201/phet-io-wrappers/phet-io-wrappers-tests.html?sim=hookes-law
9 out of 9 tests passed. 0 failed.

Approximately 4/2/2020, 6:36:58 PM
```

**Comment by pixelzoom** [comment]
Thanks @KatieWoe. Fixed in the above commit. Closing
